theme: jekyll-theme-minimal
name: OSAB Documentation
description: Documentation for the Open Source Autonomous Boat project. Visit us at https://osab.xyz/ or join our discord server here: https://discord.gg/C5H9EE7Rp3
url: "https://docs.osab.xyz/"
logo: logo final clear bg.png
